version: '3.8'

services:
  api:
    build: .
    container_name: desafio_uol_api
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app/main.py"]
